name: mongo_fixtures
description: Fixtures for MongoDb
version: 0.0.3
author: Vladimir Shushkov <vladimir@shushkov.ru>
homepage: https://github.com/vshushkov/mongo_fixtures
dependencies:
  mongo_dart: '>=0.1.45 <0.2.0'
dev_dependencies:
  unittest: any
